config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :brands do
  	resources :cosmetics do
  		collection { post :import }
  	end
  end
  root 'brands#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
	has_many :cosmetics
	validates_presence_of :brand, presence: true, length: {minimum:1}
end

app/models/cosmetic.rb
class Cosmetic < ApplicationRecord
  belongs_to :brand, optional: true

  	require 'csv'

  	def Cosmetic.import(file, brand_id)
		CSV.foreach(file.path, encoding:'utf-8:utf-8', headers: true) do |row|
			c = Cosmetic.new
			c.cate = row[0]
			c.sub_cate = row[1]
			c.pdName = row[2]
			c.pdImg = row[3]
			c.brand_id = brand_id.id
			c.save!			
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :set_charset

  def set_charset
  	headers["Content-type"] = "text/html; charset=euc-kr"
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
	def new
		@brand = Brand.new
	end

	def index
		@brands = Brand.all.order('brands.created_at DESC')
	end

	def update
		@brand = Brand.find(params[:id])

		if @brand.update(brand_params)
			redirect_to @brand
		else
			render 'edit'
		end
	end

	def create
		@brand = Brand.new(brand_params)

		if @brand.save
			redirect_to brand_path(@brand)
		else
			render 'new'
		end
	end

	def edit
		@brand = Brand.find(params[:id])
	end

	def show
		@brand = Brand.find(params[:id])
	end

	def destroy
		@brand = Brand.find(params[:id])
		@brand.destroy
		redirect_to brands_path
	end

	private
		def brand_params
			params.require(:brand).permit(:brand, :crawler)
		end
end

app/controllers/cosmetics_controller.rb
class CosmeticsController < ApplicationController
	def new
		@brand = Brand.find(params[:brand_id])
		@cosmetic = @brand.cosmetics.new
	end

	def show
		@brand = Brand.find(params[:brand_id])
		@cosmetic = @brand.cosmetics.find(params[:id])
	end

	def create
		@brand = Brand.find(params[:brand_id])
		@cosmetic = @brand.cosmetics.create(cosmetic_params)

		if @cosmetic.save
			redirect_to brand_cosmetic_path(@brand, @cosmetic)
		else
			render 'new'
		end
	end

	def index

	end

	def update
		@brand = Brand.find(params[:brand_id])
		@cosmetic = @brand.cosmetics.find(params[:id])

		if @cosmetic.update(cosmetic_params)
			redirect_to brand_cosmetic_path(@brand, @cosmetic)
		else
			render 'edit'
		end
	end

	def edit
		@brand = Brand.find(params[:brand_id])
		@cosmetic = @brand.cosmetics.find(params[:id])
	end

	def import
		@brand = Brand.find(params[:brand_id])
		Cosmetic.import(params[:file], @brand)
		redirect_to brands_path
	end

	def destroy
		@brand = Brand.find(params[:brand_id])
		@cosmetic = @brand.cosmetics.find(params[:id])

		@cosmetic.destroy
		redirect_to brand_path(@brand)
	end

	private
		def cosmetic_params
			params.require(:cosmetic).permit(:cate, :sub_cate, :pdName, :pdImg)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_version
		"3.3.7"
	end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/cosmetics_helper.rb
module CosmeticsHelper
end

app/views/brands/edit.html.erb
<h1>Add New Brand</h1>

<%= form_for :brand, url: brand_path(@brand), method: :patch do |f| %>
	<% if @brand.errors.any? %>
	<div>
		<h2><%= pluralize(@brand.errors.count, "error") %> prohibited this article from being saved: </h2>
		<ul>
			<% @brand.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<p>
		<%= f.label :brand %><br>
		<%= f.text_field :brand %><br>
	</p>

	<p>
		<%= f.label :crawler %><br>
		<%= f.text_field :crawler %><br>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

<p>
	<%= link_to 'Back', brands_path %>
</p>

app/views/brands/index.html.erb
<div class="beauty_main">
	<%= image_tag "logo2.png", :width => 400 %></h1>
</div>

<div class="container">

<p>
	<%= link_to 'New Brand', new_brand_path, class: "btn btn-default" %>
</p>

<table class="table table-hover">
	<tr>
		<th> ID </th>
		<th> Brand Name </th>
		<th> Crawler </th>
		<th> Time </th>
    <th> </th>
	</tr>

	<% @brands.each do |brand| %>
		<td><%= brand.id %></td>
		<td>
			<%= link_to brand.brand, brand_path(brand) %>
			<% if brand.created_at > Time.now - 3.days %>
				<span class="badge new">new</span>
			<% end %>
			<% if brand.created_at > Time.now - 3.days %>
				<span class="badge update">update</span>
			<% end %>
		</td>
		<td><%= brand.crawler %></td>
		<td><%= brand.created_at.strftime("%y.%m.%d, %H:%M") %></td>
		<td><%= link_to 'Destroy', brand_path(brand), method: :delete, data: { confirm: "Are you sure?"} %></td>

    </tr>
	<% end %>
</table>
</div>

app/views/brands/new.html.erb
<div class="beauty_main">
  <%= image_tag "logo2.png", :width => 400 %></h1>
</div>

<div class="container">
	<%= form_for :brand, url: brands_path do |f| %>
	<% if @brand.errors.any? %>
	<div class="panel panel-danger">
		<div class="panel-heading">
			<%= pluralize(@brand.errors.count, "error") %> prohibited this article from being saved:
		</div>

		<div class="panel-body">
		<ul>
			<% @brand.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
		</div>
	</div>
	<% end %>

  <div class="form-horizontal">
  	<div class="form-group">
  	<%= f.label :brand, class: "col-sm-2 control-label" %>
  		<div class="col-sm-10">
    		<%= f.text_field :brand, class: "col-sm-10 form-control", placeholder: "Input Cosmetic Brand Name" %>
    	</div>
    </div>
  </div>

  <div class="form-horizontal">
  	<div class="form-group">
  	<%= f.label :crawler, class: "col-sm-2 control-label" %>
  		<div class="col-sm-10">
    		<%= f.text_field :crawler, class: "form-control col-sm-10", placeholder: "Who Collected This Data" %>
    	</div>
    </div>
  </div>

  <div class="form-group col-sm-offset-2 col-sm-10">
    <%= f.submit class: "btn btn-default" %>
    <%= link_to 'Back to Page', brands_path, class: "btn btn-default" %>
  </div>

<% end %>

</div>

app/views/brands/show.html.erb
<div class="beauty_main">
  <%= link_to brands_path do %>
    <%= image_tag "logo2.png", :width => 400 %>
  <% end %>
</div>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <div class="navbar-brand">
        <%= @brand.brand %>
      </div>
    </div>

    <ul class="nav navbar-nav">
      <% category = Cosmetic.where(brand_id: @brand).select(:cate).distinct %>
      <% cate_cnt = category.count %>
        <% for i in 0..cate_cnt-1 do %>
          <li class="dropdown">
            <% cateName = category[i][:cate] %>
            <% sub_category = Cosmetic.where(brand_id: @brand, cate: cateName).select(:sub_cate).distinct %>
            <% sub_cnt = sub_category.count %>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= cateName %><span class="badge"><%= sub_cnt %></span><span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <% for j in 0..sub_cnt-1 do %>
                <% sub_Name = sub_category[j][:sub_cate] %>
                  <li><%= link_to sub_Name %><li>
                <% end %>
              </ul>
          </li>
        <% end %>
    </ul>
  </div>
</nav>

<div class="container">
  <div class="input-group">
    <div class="custom-file">
    <%= form_tag import_brand_cosmetics_path(@brand), multipart: true do %>
      <%= file_field_tag :file, class: "custom-file-input" %>
      <%= submit_tag "CSV Import" %>
    <% end %>
    </div>
  </div>

  <p class="add-cosmetic"><%= link_to '개별 화장품 추가하기', new_brand_cosmetic_path(@brand) %></p>

  <h2>Cosmetics List</h2>

  <% @brand.cosmetics.each do |cosmetic| %>
    <%= link_to brand_cosmetic_path(@brand, cosmetic) do %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <div class="notice">
          <% if cosmetic.created_at > Time.now - 3.days %>
            <span class="badge new">new</span>
          <% end %>
          <% if cosmetic.updated_at > Time.now - 3.days %>
            <span class="badge update">update</span>
          <% end %>
        </div>

        <%= image_tag cosmetic.pdImg %>
        <% end %>

        <div class="caption">
          <h4><%= truncate cosmetic.pdName, length: 40%></h4>
          <p><%= cosmetic.cate %> > <%= cosmetic.sub_cate%></p>
        </div>

        <div class="button">
          <p>
            <%= link_to 'Edit', edit_brand_cosmetic_path(@brand, cosmetic), class: "btn btn-primary"%>
            <%= link_to 'Destroy', [cosmetic.brand, cosmetic], class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure?" } %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>

app/views/cosmetics/edit.html.erb
<h1>Edit Cosmetic</h1>

<%= form_for :cosmetic, url: brand_cosmetic_path(@brand), method: :patch do |f| %>

	<p>
		<%= f.label :category %><br>
		<%= f.text_field :cate %><br>
	</p>

	<p>
		<%= f.label :sub_category %><br>
		<%= f.text_field :sub_cate %><br>
	</p>

	<p>
		<%= f.label :Product_Name %><br>
		<%= f.text_field :pdName %><br>
	</p>

	<p>
		<%= f.label :Product_Img %><br>
		<%= f.text_field :pdImg %><br>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

<p>
	<%= link_to 'Back', brands_path %>
</p>

app/views/cosmetics/new.html.erb
<div class = "beauty_main">
	<h1>Add Cosmetic <small>Beauty_project</small></h1>
</div>

<div class = "container">
<%= form_for([@brand, @brand.cosmetics.build]) do |f| %>

  <div class="form-horizontal">
  	<div class="form-group">
  	<%= f.label :category, class: "col-sm-2 control-label" %>
  		<div class="col-sm-10">
    		<%= f.text_field :cate, class: "col-sm-10 form-control", placeholder: "Input Cosmetic Category" %>
    	</div>
    </div>
  </div>

  <div class="form-horizontal">
  	<div class="form-group">
  	<%= f.label :Sub_Category, class: "col-sm-2 control-label" %>
  		<div class="col-sm-10">
    		<%= f.text_field :sub_cate, class: "col-sm-10 form-control", placeholder: "Input Cosmetic Sub Category" %>
    	</div>
    </div>
  </div>  

  <div class="form-horizontal">
  	<div class="form-group">
  	<%= f.label :Product_Name, class: "col-sm-2 control-label" %>
  		<div class="col-sm-10">
    		<%= f.text_field :pdName, class: "col-sm-10 form-control", placeholder: "Input Cosmetic Name" %>
    	</div>
    </div>
  </div>  

  <div class="form-horizontal">
  	<div class="form-group">
  	<%= f.label :Product_Img, class: "col-sm-2 control-label" %>
  		<div class="col-sm-10">
    		<%= f.text_field :pdImg, class: "col-sm-10 form-control", placeholder: "Input Cosmetic Image Path" %>
    	</div>
    </div>
  </div>

  <div class="form-group col-sm-offset-2 col-sm-10">
    <%= f.submit class: "btn btn-default" %>
    <%= link_to 'Back to Cosmetic List Page', brands_path, class: "btn btn-default" %>
  </div>
<% end %>
</div>

app/views/cosmetics/show.html.erb
<h1>Show Cosmetic</h1>

<p>
	<%= link_to 'Edit', edit_brand_cosmetic_path(@brand, @cosmetic)%>
</p>

<p>
	<strong>Category</strong>
	<%= @cosmetic.cate %>
</p>

<P>
	<strong>Sub Category</strong>
	<%= @cosmetic.sub_cate %>
</P>

<p>
	<strong>Product Name</strong>
	<%= @cosmetic.pdName %>
</p>

<p>
	<strong>Product Image</strong>
	<%= @cosmetic.pdImg %>
</p>

<p>
	<%= link_to 'Back to Cosmetic List', brand_path(@brand) %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Check</title>
    <%= csrf_meta_tags %>

		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

		<!-- Optional theme -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

		<!-- Latest compiled and minified JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://js.stripe.com/v1/" %>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/moonspam/NanumSquare@1.0/nanumsquare.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>